version: '3.8'
services:
  maven:
    image: einsteinlevel/maven:latest
    volumes:
      -type: "volume"
       source: exchange
       target: /boxfuse-sample-java-war-hello/target

  tomcat: 
    image: einsteinlevel/alpine-tomcat9:tagname
    ports: 
      - "80:8080"
    volumes:
      - "exchange:/opt/tomcat/webapps"
    
volumes:
  exchange:
