---
version: '3.8'
services:

  maven:

    image: 178.154.200.52:8123/$ImageName:latest
    volumes:
      - type: volume
        source: exchange
        target: /boxfuse-sample-java-war-hello/target

  tomcat:

    image: einsteinlevel/alpine-tomcat9
    ports: 
      - "80:8080"
    volumes:
      - "exchange:/opt/tomcat/webapps"
    
volumes:
  exchange: