---
version: '3.8'
services:

  maven:

    image: einsteinlevel/maven:latest
    volumes:
      - type: volume
        source: exchange
        target: /boxfuse-sample-java-war-hello/target    
volumes:
  exchange: